name: Deploy to dev

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: app-dev.yaml
        version: v1
        project_id: ${{ secrets.GCP_PROJECT_DEV }}
        credentials: ${{ secrets.GCP_CREDENTIALS_DEV }}

    - name: Test
      run: curl "${{ steps.deploy.outputs.url }}"