name: Deploy to dev

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  testing:
    name: Run unit test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm ci
      - run: npm run test

  deploy:
    needs: testing
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: app-dev.yaml
        version: v1
        project_id: ${{ secrets.GCP_PROJECT_DEV }}
        credentials: ${{ secrets.GCP_CREDENTIALS_DEV }}

    - name: Test
      run: curl "${{ steps.deploy.outputs.url }}"