name: Testing

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  testing:
    name: Run pipeline
    runs-on: ubuntu-latest
    env:
      HOST: localhost
      PORT: 1337
      APP_KEYS: Ock6vJB1fklvV2j6+ojTQw,LGk6Ee2hFR8izAXtgJ8N+g,5kp21juVV2qnRsiBbNiCQg,l6fX7K8ZlZuuesvFEVlHuw
      API_TOKEN_SALT: S4Y5iNoCrQ5VHezKeBTIdw
      ADMIN_JWT_SECRET: WfFyiMCOoEi7+5w2rW1KPw
      JWT_SECRET: sR+2EadCG0J5WQxUb7HG9A
      FOOD_ENDPOINT_API: https://api.edamam.com
      FOOD_API_APP_ID: 07d50733
      FOOD_API_APP_KEY: 80fcb49b500737827a9a23f7049653b9
      TRANSFER_TOKEN_SALT: 8f5258f11b2dab91ef9829af9ee0faf898d5d0b4f4b754cf09532e4b1384c84a
      NODE_ENV: test
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        env:
          HOST: localhost
          PORT: 1337
          APP_KEYS: Ock6vJB1fklvV2j6+ojTQw,LGk6Ee2hFR8izAXtgJ8N+g,5kp21juVV2qnRsiBbNiCQg,l6fX7K8ZlZuuesvFEVlHuw
          API_TOKEN_SALT: S4Y5iNoCrQ5VHezKeBTIdw
          JWT_SECRET: sR+2EadCG0J5WQxUb7HG9A
          FOOD_ENDPOINT_API: https://api.edamam.com
          FOOD_API_APP_ID: 07d50733
          FOOD_API_APP_KEY: 80fcb49b500737827a9a23f7049653b9
          NODE_ENV: test
          ENV: test
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm ci
      - run: npm run test